name: kumo_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.3
  http: 0.13.4
  email_validator: 2.0.1
  hydrated_bloc: 9.0.0-dev.2
  path_provider: ^2.0.10
  flutter_colorpicker: ^1.0.3
  cupertino_icons: ^1.0.4
  tuple: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
